version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:4.3.0-management
    ports:
      - "5672:5672"   # Порт для коду
      - "15672:15672" # Адмінка (гість/гість)

  catalog-db:
    image: postgres:18.3-bookworm
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_CATALOG_DB}
    ports:
      - "5432:5432"
    volumes:
      - ${PROJECT_ROOT}/out/catalog-pg-data:/var/lib/postgresql
    restart: always
  
  identity-db:
    image: postgres:18.3-bookworm
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_IDENTITY_DB}
    ports:
      - "5433:5432"
    volumes:
      - ${PROJECT_ROOT}/out/identity-pg-data:/var/lib/postgresql
    restart: always

  order-db:
    image: postgres:18.3-bookworm
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_ORDER_DB}
    ports:
      - "5434:5432"
    volumes:
      - ${PROJECT_ROOT}/out/order-pg-data:/var/lib/postgresql
    restart: always